# Generated by Django 3.1.6 on 2021-02-23 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('department', models.CharField(choices=[('COM', 'COM'), ('IT', 'IT'), ('ETS', 'ETS'), ('SIK', 'SIK')], max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('language', models.CharField(choices=[('Java', 'Java'), ('Python', 'Python'), ('Javascript', 'Javascript'), ('PHP', 'PHP'), ('C', 'C'), ('C++', 'C++'), ('C#', 'C++')], max_length=200)),
                ('project_type', models.CharField(choices=[('Web Application', 'Web Application'), ('Desktop', 'Desktop'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Mobile Application', 'Mobile Appication')], max_length=200)),
                ('project_concept', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
